- name: Deploy a web application
  hosts: db_and_server1,db_and_server2
  tasks:
    - name: install all required dependencies
      apt: name={{ item }} state=present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml
