---
# tasks file for mysql_db
 - name: install mysql database
          apt: name={{ item }} state=present
          with_items:
            - mysql-server
            - mysql-client

    - name: start mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: create application database
      mysql_db: name={{ db_name }} state=present

    - name: create database users
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:ALL'
        state: present
        host: '%'